[package]
name = "rapid-core"
version = "0.1.0"
edition = "2024"

[dependencies]
rapid-types = {path="../rapid-types"}
rapid-macros = {path="../rapid-macros"}

talky.workspace = true
heapless.workspace = true
embassy-executor.workspace = true
embassy-time.workspace = true
embassy-futures.workspace = true
embassy-sync.workspace = true
static_cell.workspace = true
serde.workspace = true
trouble-host.workspace = true
bt-hci.workspace = true
const_panic.workspace = true
sequential-storage.workspace = true
embedded-storage.workspace = true
embedded-storage-async.workspace = true
embassy-embedded-hal.workspace = true
postcard.workspace = true
[dev-dependencies]
tokio.workspace = true
