[package]
name = "ivy-core"
version = "0.1.0"
edition = "2024"

[dependencies]
ivy-types = {path="../ivy-types"}
ivy-macros = {path="../ivy-macros"}

talky.workspace = true
heapless.workspace = true
embassy-executor.workspace = true
embassy-time.workspace = true
embassy-futures.workspace = true
embassy-sync.workspace = true
static_cell.workspace = true
serde.workspace = true
const_panic.workspace = true
sequential-storage.workspace = true
embedded-storage.workspace = true
embedded-storage-async.workspace = true
embassy-embedded-hal.workspace = true
postcard.workspace = true
serde-json-core.workspace = true
serde_json.workspace = true
pin-project.workspace = true
tracing.workspace = true
mqttrust.workspace = true
embassy-net.workspace = true
embedded-tls.workspace = true
thiserror.workspace = true
paste.workspace = true

[dev-dependencies]
tokio.workspace = true
tracing-subscriber.workspace = true
critical-section.workspace = true
